language: "node_js"
node_js:
  - '12'

sudo: required

services:
  - docker

script: 'true'

after_success:
  - docker build -t mrwin95/multi-client ./client
  - docker build -t mrwin95/multi-nginx ./nginx
  - docker build -t mrwin95/multi-server ./server
  - docker build -t mrwin95/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mrwin95/multi-client
  - docker push mrwin95/multi-nginx
  - docker push mrwin95/multi-server
  - docker push mrwin95/multi-worker
#Login to docker cli

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-1-009876694182"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

